users = [
    {
        'user_id': 1,
        'name': 'Bernadya Ribka',
        'date_of_birth': '2004-03-16',
        'domicile_city': 'South Jakarta',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281204579834',
        'email': 'bernadya.ribka@gmail.com',
        'gender': 'F',
        'legal_id_no': '3174055603040001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 2,
        'name': 'Ragnar Oratmangoen',
        'date_of_birth': '1998-10-12',
        'domicile_city': 'Denderleeuw',
        'domicile_country': 'Belgium',
        'nationality_country': 'Indonesia',
        'phone_number': '+32748384028',
        'email': 'ragnar.oratmangoen@gmail.com',
        'gender': 'M',
        'legal_id_no': '3171012101980001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 3,
        'name': 'Aji Santoso',
        'date_of_birth': '1970-04-06',
        'domicile_city': 'Pekanbaru',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281984646392',
        'email': 'aji.santoso@gmail.com',
        'gender': 'M',
        'legal_id_no': '3573030604700001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 4,
        'name': 'Yesaya Desnam',
        'date_of_birth': '1985-06-25',
        'domicile_city': 'Wamena',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281374649348',
        'email': 'yesaya.desnam@gmail.com',
        'gender': 'M',
        'legal_id_no': '9101012506850001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 5,
        'name': 'Yanto Basna',
        'date_of_birth': '1995-06-12',
        'domicile_city': 'Prachuap Khiri Khan',
        'domicile_country': 'Thailand',
        'nationality_country': 'Indonesia',
        'phone_number': '+668474923472',
        'email': 'yanto.basna@gmail.com',
        'gender': 'M',
        'legal_id_no': '9271071206950001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 6,
        'name': 'Talaohu Musafri',
        'date_of_birth': '1982-02-19',
        'domicile_city': 'Batam',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281346581093',
        'email': 't.a.musafri@gmail.com',
        'gender': 'M',
        'legal_id_no': '8204081902820001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 7,
        'name': 'Mukti Entut',
        'date_of_birth': '1991-04-07',
        'domicile_city': 'Yogyakarta',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281364583921',
        'email': 'mukti.entut@gmail.com',
        'gender': 'M',
        'legal_id_no': '3471140704910001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 8,
        'name': 'Zahra Muzdalifah',
        'date_of_birth': '2001-04-04',
        'domicile_city': 'Osaka',
        'domicile_country': 'Japan',
        'nationality_country': 'Indonesia',
        'phone_number': '+819374374920',
        'email': 'zahra.muzdalifah@gmail.com',
        'gender': 'F',
        'legal_id_no': '3173084404010001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 9,
        'name': 'Noa Leatomu',
        'date_of_birth': '2003-11-07',
        'domicile_city': 'Genk',
        'domicile_country': 'Belgium',
        'nationality_country': 'Indonesia',
        'phone_number': '+32937587320',
        'email': 'noa.leatomu@gmail.com',
        'gender': 'F',
        'legal_id_no': '3171014711030001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 10,
        'name': 'Djenna de Jong',
        'date_of_birth': '2005-09-14',
        'domicile_city': 'Breda',
        'domicile_country': 'Netherlands',
        'nationality_country': 'Indonesia',
        'phone_number': '+318843940312',
        'email': 'djenna.de.jong@gmail.com',
        'gender': 'F',
        'legal_id_no': '3171015409050001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 11,
        'name': 'Talia Grossman',
        'date_of_birth': '2002-03-08',
        'domicile_city': 'Columbia',
        'domicile_country': 'United States',
        'nationality_country': 'Indonesia',
        'phone_number': '+14757384712',
        'email': 'talia.grossman@gmail.com',
        'gender': 'F',
        'legal_id_no': '3171014803020001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 12,
        'name': 'Safira Ika',
        'date_of_birth': '2003-04-21',
        'domicile_city': 'South Jakarta',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281385493021',
        'email': 'safira.ika@gmail.com',
        'gender': 'F',
        'legal_id_no': '3171036104030001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 13,
        'name': 'Legimin Raharjo',
        'date_of_birth': '1982-05-10',
        'domicile_city': 'Medan',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281876473832',
        'email': 'legimin.raharjo@gmail.com',
        'gender': 'M',
        'legal_id_no': '1271121005820001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 14,
        'name': 'Usep Munandar',
        'date_of_birth': '1981-12-17',
        'domicile_city': 'Bandung',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281485632843',
        'email': 'usep.munandar@gmail.com',
        'gender': 'M',
        'legal_id_no': '3273051712810001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 15,
        'name': 'Oza Rangkuti',
        'date_of_birth': '1991-12-05',
        'domicile_city': 'South Jakarta',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281358439212',
        'email': 'oza.rangkuti@gmail.com',
        'gender': 'M',
        'legal_id_no': '3174020512910001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 16,
        'name': 'Rita Ratu Tawon',
        'date_of_birth': '1990-03-25',
        'domicile_city': 'Yogyakarta',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281563832483',
        'email': 'rita.ratu.tawon@gmail.com',
        'gender': 'F',
        'legal_id_no': '3403086503900001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 17,
        'name': 'Fathia Izzati',
        'date_of_birth': '1994-09-26',
        'domicile_city': 'South Jakarta',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281547382912',
        'email': 'fathia.izzati@gmail.com',
        'gender': 'F',
        'legal_id_no': '3174066609940001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 18,
        'name': 'Rocky Gerung',
        'date_of_birth': '1959-01-20',
        'domicile_city': 'South Jakarta',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281893483921',
        'email': 'rocky.gerung@gmail.com',
        'gender': 'M',
        'legal_id_no': '7171042001590001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 19,
        'name': 'Hugo Samir',
        'date_of_birth': '2004-03-16',
        'domicile_city': 'Kediri',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281893483212',
        'email': 'hugo.samir@gmail.com',
        'gender': 'M',
        'legal_id_no': '3578021603040001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 20,
        'name': 'Yudha Brajamusti',
        'date_of_birth': '1991-09-17',
        'domicile_city': 'East Jakarta',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281384459374',
        'email': 'yudha.brajamusti@gmail.com',
        'gender': 'M',
        'legal_id_no': '3175041709910001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 21,
        'name': 'Windah Basudara',
        'date_of_birth': '1992-03-14',
        'domicile_city': 'West Jakarta',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281893464732',
        'email': 'windah.basudara@gmail.com',
        'gender': 'M',
        'legal_id_no': '7171051403920001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
        {
        'user_id': 22,
        'name': 'Bayu Gatra',
        'date_of_birth': '1991-11-11',
        'domicile_city': 'Padang',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281783463293',
        'email': 'bayu.gatra@gmail.com',
        'gender': 'M',
        'legal_id_no': '3509301111910001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 23,
        'name': 'Rizky Pora',
        'date_of_birth': '1989-11-22',
        'domicile_city': 'Banjarmasin',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281842283048',
        'email': 'rizky.pora@gmail.com',
        'gender': 'M',
        'legal_id_no': '8271022211890001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 24,
        'name': 'Ronaldo Kwateh',
        'date_of_birth': '2004-10-19',
        'domicile_city': 'Pak Kret',
        'domicile_country': 'Thailand',
        'nationality_country': 'Indonesia',
        'phone_number': '+663840382013',
        'email': 'ronaldo.kwateh@gmail.com',
        'gender': 'M',
        'legal_id_no': '3471071910040001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 25,
        'name': 'Ilija Spasojevic',
        'date_of_birth': '1987-09-11',
        'domicile_city': 'South Jakarta',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281739483202',
        'email': 'ilija.spasojevic@gmail.com',
        'gender': 'M',
        'legal_id_no': '5104031109870001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 26,
        'name': 'Muhammad Danurwindo',
        'date_of_birth': '1951-05-15',
        'domicile_city': 'South Jakarta',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281947820183',
        'email': 'danurwindo@gmail.com',
        'gender': 'M',
        'legal_id_no': '3306060515510001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 27,
        'name': 'Yabes Roni',
        'date_of_birth': '1995-02-06',
        'domicile_city': 'Gianyar',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6285293753821',
        'email': 'yabes.roni@gmail.com',
        'gender': 'M',
        'legal_id_no': '5305040602950001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 28,
        'name': 'Andi Wijaya',
        'date_of_birth': '1985-07-20',
        'domicile_city': 'Bekasi',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281384402938',
        'email': 'andi.wijaya@gmail.com',
        'gender': 'M',
        'legal_id_no': '3275052007850001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 29,
        'name': 'Anggi Marito',
        'date_of_birth': '2002-03-06',
        'domicile_city': 'North Jakarta',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6289347583921',
        'email': 'anggi.marito@gmail.com',
        'gender': 'F',
        'legal_id_no': '1202014603020001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 30,
        'name': 'Gregoria Mariska',
        'date_of_birth': '1999-08-11',
        'domicile_city': 'East Jakarta',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281920038103',
        'email': 'gregoria.mariska@gmail.com',
        'gender': 'F',
        'legal_id_no': '3312015108990001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 31,
        'name': 'Lusia Chebotina',
        'date_of_birth': '1997-04-26',
        'domicile_city': 'Moscow',
        'domicile_country': 'Russia',
        'nationality_country': 'Russia',
        'phone_number': '+74843201921',
        'email': 'lusia.chebotina@yandex.com',
        'gender': 'F',
        'legal_id_no': '0140394839',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 32,
        'name': 'Sergey Shnurov',
        'date_of_birth': '1973-04-13',
        'domicile_city': 'Berlin',
        'domicile_country': 'Germany',
        'nationality_country': 'Russia',
        'phone_number': '+4937282938302',
        'email': 'sergey.shnurov@yandex.com',
        'gender': 'M',
        'legal_id_no': '0245485932',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 33,
        'name': 'Aleksandr Golovin',
        'date_of_birth': '1996-05-30',
        'domicile_city': 'Monaco',
        'domicile_country': 'Monaco',
        'nationality_country': 'Russia',
        'phone_number': '+37746331023',
        'email': 'aleksandr.golovin@yandex.com',
        'gender': 'M',
        'legal_id_no': '0743484320',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 34,
        'name': 'Maksim Glushenkov',
        'date_of_birth': '1999-07-28',
        'domicile_city': 'Saint Petersburg',
        'domicile_country': 'Russia',
        'nationality_country': 'Russia',
        'phone_number': '+73649221923',
        'email': 'maksim.glushenkov@yandex.com',
        'gender': 'M',
        'legal_id_no': '1523203943',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 35,
        'name': 'Alsou Abramova',
        'date_of_birth': '1983-06-27',
        'domicile_city': 'Moscow',
        'domicile_country': 'Russia',
        'nationality_country': 'Russia',
        'phone_number': '+74849328312',
        'email': 'alsou.abramova@yandex.com',
        'gender': 'F',
        'legal_id_no': '2530329102',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 36,
        'name': 'Mykhailo Mudryk',
        'date_of_birth': '2001-01-05',
        'domicile_city': 'London',
        'domicile_country': 'United Kingdom',
        'nationality_country': 'Ukraine',
        'phone_number': '+4459503291232',
        'email': 'mykhailo.mudryk@gmail.com',
        'gender': 'M',
        'legal_id_no': '2001010500001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 37,
        'name': 'Aliaksandr Hleb',
        'date_of_birth': '1981-05-01',
        'domicile_city': 'Minsk',
        'domicile_country': 'Belarus',
        'nationality_country': 'Belarus',
        'phone_number': '+375394302321',
        'email': 'aliaksandr.hleb@yandex.com',
        'gender': 'M',
        'legal_id_no': '012834322',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 38,
        'name': 'Taras Stepanenko',
        'date_of_birth': '1989-08-08',
        'domicile_city': 'Kiev',
        'domicile_country': 'Ukraine',
        'nationality_country': 'Ukraine',
        'phone_number': '+38029328219',
        'email': 'taras.stepanenko@gmail.com',
        'gender': 'M',
        'legal_id_no': '1989080800001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 39,
        'name': 'Nadia Meikher',
        'date_of_birth': '1982-04-10',
        'domicile_city': 'Kiev',
        'domicile_country': 'Ukraine',
        'nationality_country': 'Ukraine',
        'phone_number': '+38049430212',
        'email': 'nadia.meikher@gmail.com',
        'gender': 'F',
        'legal_id_no': '1982041000001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 40,
        'name': 'Alena Lanskaya',
        'date_of_birth': '1985-09-07',
        'domicile_city': 'Mogilev',
        'domicile_country': 'Belarus',
        'nationality_country': 'Belarus',
        'phone_number': '+375394302192',
        'email': 'alena.lanskaya@gmail.com',
        'gender': 'F',
        'legal_id_no': '043932012',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 41,
        'name': 'Sergey Khizhnichenko',
        'date_of_birth': '1991-07-17',
        'domicile_city': 'Oskemen',
        'domicile_country': 'Kazakhstan',
        'nationality_country': 'Kazakhstan',
        'phone_number': '+7293043930',
        'email': 'sergey.khizhnichenko@yandex.com',
        'gender': 'M',
        'legal_id_no': '910717000001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 42,
        'name': 'Sabina Altynbekova',
        'date_of_birth': '1996-11-05',
        'domicile_city': 'Almaty',
        'domicile_country': 'Kazakhstan',
        'nationality_country': 'Kazakhstan',
        'phone_number': '+73940391021',
        'email': 'sabina.altynbekova@yandex.com',
        'gender': 'F',
        'legal_id_no': '961105000001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 43,
        'name': 'Manuchekhr Dzhalilov',
        'date_of_birth': '1990-09-27',
        'domicile_city': 'Dushanbe',
        'domicile_country': 'Tajikistan',
        'nationality_country': 'Tajikistan',
        'phone_number': '+38029328219',
        'email': 'manuchekhr.dzhalilov@yandex.com',
        'gender': 'M',
        'legal_id_no': '4849831029381',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 44,
        'name': 'Abbosbek Fayzullaev',
        'date_of_birth': '2003-10-03',
        'domicile_city': 'Moscow',
        'domicile_country': 'Russia',
        'nationality_country': 'Uzbekistan',
        'phone_number': '+79458301923',
        'email': 'abbosbek.fayzullaev@yandex.com',
        'gender': 'M',
        'legal_id_no': '493743921038293',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 45,
        'name': 'Joel Kojo',
        'date_of_birth': '1998-08-21',
        'domicile_city': 'Samarkand',
        'domicile_country': 'Uzbekistan',
        'nationality_country': 'Kyrgyzstan',
        'phone_number': '+998129384739',
        'email': 'joel.kojo@yandex.com',
        'gender': 'M',
        'legal_id_no': '8475392',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 46,
        'name': 'Henrikh Mkhitaryan',
        'date_of_birth': '1989-01-21',
        'domicile_city': 'Milan',
        'domicile_country': 'Italy',
        'nationality_country': 'Armenia',
        'phone_number': '+39459420392',
        'email': 'henrikh.mkhitaryan@yandex.com',
        'gender': 'M',
        'legal_id_no': '0130430321',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 47,
        'name': 'Sirusho Harutyunyan',
        'date_of_birth': '1987-01-07',
        'domicile_city': 'Yerevan',
        'domicile_country': 'Armenia',
        'nationality_country': 'Armenia',
        'phone_number': '+37439483821s',
        'email': 'sirusho.harutyunyan@yandex.com',
        'gender': 'F',
        'legal_id_no': '0148493212',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 48,
        'name': 'Gunel Zeynalova',
        'date_of_birth': '1985-10-25',
        'domicile_city': 'Istanbul',
        'domicile_country': 'Turkey',
        'nationality_country': 'Azerbaijan',
        'phone_number': '+906483921',
        'email': 'gunel.zeynalova@ygmail.com',
        'gender': 'F',
        'legal_id_no': '5637392',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 49,
        'name': 'Marina Djundiet',
        'date_of_birth': '1996-10-15',
        'domicile_city': 'Rybnitsa',
        'domicile_country': 'Moldova',
        'nationality_country': 'Moldova',
        'phone_number': '+3734044701',
        'email': 'marina.djundiet@gmail.com',
        'gender': 'F',
        'legal_id_no': '20483984',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 50,
        'name': 'Marija Naumova',
        'date_of_birth': '1973-06-23',
        'domicile_city': 'Riga',
        'domicile_country': 'Latvia',
        'nationality_country': 'Latvia',
        'phone_number': '+37130942129',
        'email': 'marija.naumova@gmail.com',
        'gender': 'F',
        'legal_id_no': '23067310010',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 51,
        'name': 'Arda Guler',
        'date_of_birth': '2005-02-25',
        'domicile_city': 'Madrid',
        'domicile_country': 'Spain',
        'nationality_country': 'Turkey',
        'phone_number': '+34439204830',
        'email': 'arda.guler@gmail.com',
        'gender': 'M',
        'legal_id_no': '983423802932',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 52,
        'name': 'Simge Sagin',
        'date_of_birth': '1981-08-08',
        'domicile_city': 'Istanbul',
        'domicile_country': 'Turkey',
        'nationality_country': 'Turkey',
        'phone_number': '+904837292',
        'email': 'simge.sagin@gmail.com',
        'gender': 'F',
        'legal_id_no': '338910932833',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 53,
        'name': 'Konstantinos Argyros',
        'date_of_birth': '1986-05-21',
        'domicile_city': 'Athens',
        'domicile_country': 'Greece',
        'nationality_country': 'Greece',
        'phone_number': '+303920298329',
        'email': 'konstantinos.argyros@gmail.com',
        'gender': 'M',
        'legal_id_no': '287343324',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 54,
        'name': 'Theo Rose',
        'date_of_birth': '1997-08-08',
        'domicile_city': 'Ploiesti',
        'domicile_country': 'Romania',
        'nationality_country': 'Romania',
        'phone_number': '+403409029312',
        'email': 'theo.rose@gmail.com',
        'gender': 'F',
        'legal_id_no': '2080897290011',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 55,
        'name': 'Sardar Azmoun',
        'date_of_birth': '1995-01-01',
        'domicile_city': 'Dubai',
        'domicile_country': 'United Arab Emirates',
        'nationality_country': 'Iran',
        'phone_number': '+9710128123',
        'email': 'sardar.azmoun@gmail.com',
        'gender': 'M',
        'legal_id_no': '10398322921',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 56,
        'name': 'Ali Al-Bulaihi',
        'date_of_birth': '1989-11-21',
        'domicile_city': 'Riyadh',
        'domicile_country': 'Saudi Arabia',
        'nationality_country': 'Saudi Arabia',
        'phone_number': '+9661290123',
        'email': 'al.al-bulaihi@gmail.com',
        'gender': 'M',
        'legal_id_no': '11028934',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 57,
        'name': 'Sarit Hadad',
        'date_of_birth': '1978-09-20',
        'domicile_city': 'Tel Aviv',
        'domicile_country': 'Israel',
        'nationality_country': 'Israel',
        'phone_number': '+972578412091',
        'email': 'sarit.hadad@gmail.com',
        'gender': 'F',
        'legal_id_no': '398431029',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 58,
        'name': 'Myriam Fares',
        'date_of_birth': '1983-05-03',
        'domicile_city': 'Beirut',
        'domicile_country': 'Lebanon',
        'nationality_country': 'Lebanon',
        'phone_number': '+96173293211',
        'email': 'myriam.fares@gmail.com',
        'gender': 'F',
        'legal_id_no': '23812092',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 59,
        'name': 'Mohamed Salah',
        'date_of_birth': '1995-01-01',
        'domicile_city': 'Liverpool',
        'domicile_country': 'United Kingdom',
        'nationality_country': 'Egypt',
        'phone_number': '+4474391029129',
        'email': 'mohamed.salah@gmail.com',
        'gender': 'M',
        'legal_id_no': '92831872302842',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 60,
        'name': 'Aymen Hussein',
        'date_of_birth': '1996-03-22',
        'domicile_city': 'Al-Khor',
        'domicile_country': 'Qatar',
        'nationality_country': 'Iraq',
        'phone_number': '+97492384272',
        'email': 'aymen.hussein@gmail.com',
        'gender': 'M',
        'legal_id_no': '623721921271',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 61,
        'name': 'Mohammed Rashid',
        'date_of_birth': '1995-07-03',
        'domicile_city': 'Surabaya',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Palestine',
        'phone_number': '+6281329381209',
        'email': 'mohammed.rashid@gmail.com',
        'gender': 'M',
        'legal_id_no': '928373821',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 62,
        'name': 'Riyad Mahrez',
        'date_of_birth': '1991-02-21',
        'domicile_city': 'Jeddah',
        'domicile_country': 'Saudi Arabia',
        'nationality_country': 'Algeria',
        'phone_number': '+9662938283',
        'email': 'riyad.mahrez@gmail.com',
        'gender': 'M',
        'legal_id_no': '827343121',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 63,
        'name': 'Najoua Belyzel',
        'date_of_birth': '1981-12-15',
        'domicile_city': 'Paris',
        'domicile_country': 'France',
        'nationality_country': 'France',
        'phone_number': '+33629431281',
        'email': 'najoua.belyzel@gmail.com',
        'gender': 'F',
        'legal_id_no': '348931',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 64,
        'name': 'Quim Barreiros',
        'date_of_birth': '1947-06-19',
        'domicile_city': 'Lisbon',
        'domicile_country': 'Portugal',
        'nationality_country': 'Portugal',
        'phone_number': '+351298310293',
        'email': 'quim.barreiros@gmail.com',
        'gender': 'M',
        'legal_id_no': '42398412',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 65,
        'name': 'Rosalia Vila',
        'date_of_birth': '1992-09-25',
        'domicile_city': 'Barcelona',
        'domicile_country': 'Spain',
        'nationality_country': 'Spain',
        'phone_number': '+34289492384',
        'email': 'rosalia.vila@gmail.com',
        'gender': 'F',
        'legal_id_no': '28472039',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 66,
        'name': 'Thiago Motta',
        'date_of_birth': '1982-08-28',
        'domicile_city': 'Turin',
        'domicile_country': 'Italy',
        'nationality_country': 'Italy',
        'phone_number': '+39019323282',
        'email': 'thiago.motta@gmail.com',
        'gender': 'M',
        'legal_id_no': '820828',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 67,
        'name': 'Andreas Frege',
        'date_of_birth': '1962-06-22',
        'domicile_city': 'Dusseldorf',
        'domicile_country': 'Germany',
        'nationality_country': 'Germany',
        'phone_number': '+4903829712893',
        'email': 'andreas.frege@gmail.com',
        'gender': 'M',
        'legal_id_no': '923420',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 68,
        'name': 'Marco van Basten',
        'date_of_birth': '1964-10-31',
        'domicile_city': 'Amsterdam',
        'domicile_country': 'Netherlands',
        'nationality_country': 'Netherlands',
        'phone_number': '+313942391209',
        'email': 'marco.van.basten@gmail.com',
        'gender': 'M',
        'legal_id_no': '012938',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 69,
        'name': 'Nicklas Bendtner',
        'date_of_birth': '1988-10-16',
        'domicile_city': 'Copenhagen',
        'domicile_country': 'Denmark',
        'nationality_country': 'Denmark',
        'phone_number': '+4520930291',
        'email': 'nicklas.bendtner@gmail.com',
        'gender': 'M',
        'legal_id_no': '1016881881',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 70,
        'name': 'Khvicha Kvaratskhelia',
        'date_of_birth': '2001-02-12',
        'domicile_city': 'Naples',
        'domicile_country': 'Italy',
        'nationality_country': 'Georgia',
        'phone_number': '+39467210391',
        'email': 'khvicha.kvaratskhelia@gmail.com',
        'gender': 'M',
        'legal_id_no': '7273210938',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 71,
        'name': 'Jamie Vardy',
        'date_of_birth': '1987-01-11',
        'domicile_city': 'Leicester',
        'domicile_country': 'United Kingdom',
        'nationality_country': 'United Kingdom',
        'phone_number': '+445236282742',
        'email': 'jamie.vardy@gmail.com',
        'gender': 'M',
        'legal_id_no': '870111',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 72,
        'name': 'Roy Keane',
        'date_of_birth': '1971-08-10',
        'domicile_city': 'London',
        'domicile_country': 'United Kingdom',
        'nationality_country': 'Ireland',
        'phone_number': '+444857452103',
        'email': 'roy.keane@gmail.com',
        'gender': 'M',
        'legal_id_no': '2874362',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 73,
        'name': 'Jackson Irvine',
        'date_of_birth': '1993-03-07',
        'domicile_city': 'Hamburg',
        'domicile_country': 'Germany',
        'nationality_country': 'Australia',
        'phone_number': '+4902843328794',
        'email': 'jackson.irvine@gmail.com',
        'gender': 'M',
        'legal_id_no': '0389329',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 74,
        'name': 'Awer Mabil',
        'date_of_birth': '1995-09-15',
        'domicile_city': 'Zurich',
        'domicile_country': 'Switzerland',
        'nationality_country': 'Australia',
        'phone_number': '+41293837128',
        'email': 'awer.mabil@gmail.com',
        'gender': 'M',
        'legal_id_no': '01843981',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 75,
        'name': "Lorde Yelich-O'Connor",
        'date_of_birth': '1996-11-07',
        'domicile_city': 'Auckland',
        'domicile_country': 'New Zealand',
        'nationality_country': 'New Zealand',
        'phone_number': '+64395823',
        'email': 'lorde.yelich-oconnor@gmail.com',
        'gender': 'F',
        'legal_id_no': '732843',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 76,
        'name': 'Christian Pulisic',
        'date_of_birth': '1998-09-18',
        'domicile_city': 'Milan',
        'domicile_country': 'Italy',
        'nationality_country': 'United States',
        'phone_number': '+39387432812',
        'email': 'christian.pulisic@gmail.com',
        'gender': 'M',
        'legal_id_no': '03284732',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 77,
        'name': 'Sabrina Carpenter',
        'date_of_birth': '1999-05-11',
        'domicile_city': 'Quakertown',
        'domicile_country': 'United States',
        'nationality_country': 'United States',
        'phone_number': '+19283237281',
        'email': 'sabrina.carpenter@gmail.com',
        'gender': 'F',
        'legal_id_no': '08246237',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 78,
        'name': 'Ana Barbara',
        'date_of_birth': '1971-01-10',
        'domicile_city': 'Mexico City',
        'domicile_country': 'Mexico',
        'nationality_country': 'Mexico',
        'phone_number': '+523984347210',
        'email': 'ana.barbara@gmail.com',
        'gender': 'F',
        'legal_id_no': '71011001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 79,
        'name': 'Alphonso Davies',
        'date_of_birth': '2000-11-02',
        'domicile_city': 'Munich',
        'domicile_country': 'Germany',
        'nationality_country': 'Canada',
        'phone_number': '+493465472198',
        'email': 'alphonso.davies@gmail.com',
        'gender': 'M',
        'legal_id_no': '376432',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 80,
        'name': 'Anitta Machado',
        'date_of_birth': '1993-03-30',
        'domicile_city': 'Rio de Janeiro',
        'domicile_country': 'Brazil',
        'nationality_country': 'Brazil',
        'phone_number': '+41293837128',
        'email': 'anitta.machado@gmail.com',
        'gender': 'F',
        'legal_id_no': '03439842307',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 81,
        'name': 'Cleo Klepko',
        'date_of_birth': '1983-06-25',
        'domicile_city': 'Szczeczin',
        'domicile_country': 'Poland',
        'nationality_country': 'Poland',
        'phone_number': '+4829382746',
        'email': 'cleo.klepko@gmail.com',
        'gender': 'F',
        'legal_id_no': '19830625125',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 82,
        'name': 'Dominik Szoboszlai',
        'date_of_birth': '2000-10-25',
        'domicile_city': 'Liverpool',
        'domicile_country': 'United Kingdom',
        'nationality_country': 'Hungary',
        'phone_number': '+442744632746',
        'email': 'dominik.szoboszlai@gmail.com',
        'gender': 'M',
        'legal_id_no': '30010250011',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 83,
        'name': 'Kali Dumancic',
        'date_of_birth': '2001-08-18',
        'domicile_city': 'Sremska Mitrovica',
        'domicile_country': 'Serbia',
        'nationality_country': 'Serbia',
        'phone_number': '+38137632378',
        'email': 'kali.dumancic@gmail.com',
        'gender': 'F',
        'legal_id_no': '1808001895001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 84,
        'name': 'Alma Subasic',
        'date_of_birth': '1994-05-30',
        'domicile_city': 'Konjic',
        'domicile_country': 'Bosnia-Herzegovina',
        'nationality_country': 'Bosnia-Herzegovina',
        'phone_number': '+38728743621',
        'email': 'alma.subasic@gmail.com',
        'gender': 'F',
        'legal_id_no': '3005994155001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 85,
        'name': 'Ronela Hajati',
        'date_of_birth': '1989-09-02',
        'domicile_city': 'Tirana',
        'domicile_country': 'Albania',
        'nationality_country': 'Albania',
        'phone_number': '+493465472198',
        'email': 'ronela.hajati@gmail.com',
        'gender': 'F',
        'legal_id_no': '8909020011',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 86,
        'name': 'Andrea Andreeva',
        'date_of_birth': '1987-01-23',
        'domicile_city': 'Sofia',
        'domicile_country': 'Bulgaria',
        'nationality_country': 'Bulgaria',
        'phone_number': '+359384673821',
        'email': 'andrea.andreeva@gmail.com',
        'gender': 'F',
        'legal_id_no': '870123000',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 87,
        'name': 'Shin Tae-Yong',
        'date_of_birth': '1970-10-11',
        'domicile_city': 'Jakarta',
        'domicile_country': 'Indonesia',
        'nationality_country': 'South Korea',
        'phone_number': '+6281723618301',
        'email': 'shin.tae-yong@gmail.com',
        'gender': 'M',
        'legal_id_no': '7010111770110',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 88,
        'name': 'Jackie Chan',
        'date_of_birth': '1954-04-07',
        'domicile_city': 'Hong Kong',
        'domicile_country': 'Hong Kong',
        'nationality_country': 'Hong Kong',
        'phone_number': '+85293478217',
        'email': 'jackie.chan@gmail.com',
        'gender': 'M',
        'legal_id_no': '264273',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 89,
        'name': 'Kaoru Mitoma',
        'date_of_birth': '1997-05-20',
        'domicile_city': 'Brighton',
        'domicile_country': 'United Kingdom',
        'nationality_country': 'Japan',
        'phone_number': '+447235282163',
        'email': 'kaoru.mitoma@gmail.com',
        'gender': 'M',
        'legal_id_no': '297438283120',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 90,
        'name': 'Victor Osimhen',
        'date_of_birth': '1998-12-29',
        'domicile_city': 'Istanbul',
        'domicile_country': 'Turkey',
        'nationality_country': 'Nigeria',
        'phone_number': '+900837363',
        'email': 'victor.osimhen@gmail.com',
        'gender': 'M',
        'legal_id_no': '14824627309',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 91,
        'name': 'Asnawi Mangkualam',
        'date_of_birth': '1999-10-04',
        'domicile_city': 'Bangkok',
        'domicile_country': 'Thailand',
        'nationality_country': 'Indonesia',
        'phone_number': '+668135473084',
        'email': 'asnawi.mangkualam@gmail.com',
        'gender': 'M',
        'legal_id_no': '7371040410990001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 92,
        'name': 'Maarten Paes',
        'date_of_birth': '1998-05-14',
        'domicile_city': 'Dallas',
        'domicile_country': 'United States',
        'nationality_country': 'Indonesia',
        'phone_number': '+14298472093s',
        'email': 'maarten.paes@gmail.com',
        'gender': 'M',
        'legal_id_no': '3171011405980001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 93,
        'name': 'Marselino Ferdinan',
        'date_of_birth': '2004-09-09',
        'domicile_city': 'Oxford',
        'domicile_country': 'United Kingdom',
        'nationality_country': 'Indonesia',
        'phone_number': '+4492844739221',
        'email': 'marselino.ferdinan@gmail.com',
        'gender': 'M',
        'legal_id_no': '3175010909040001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 94,
        'name': 'Otavio Dutra',
        'date_of_birth': '1983-11-22',
        'domicile_city': 'Bojonegoro',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281932786271',
        'email': 'otavio.dutra@gmail.com',
        'gender': 'M',
        'legal_id_no': '3171012211830001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 95,
        'name': 'Osas Saha',
        'date_of_birth': '1995-02-06',
        'domicile_city': 'Bojonegoro',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281274832101',
        'email': 'osas.saha@gmail.com',
        'gender': 'M',
        'legal_id_no': '3171010602950001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 96,
        'name': 'Victor Igbonefo',
        'date_of_birth': '1985-10-10',
        'domicile_city': 'Bandung',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+628574323494',
        'email': 'victor.igbonefo@gmail.com',
        'gender': 'M',
        'legal_id_no': '3171011010850001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 97,
        'name': 'Ismed Sofyan',
        'date_of_birth': '1979-08-28',
        'domicile_city': 'Bekasi',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6285738749182',
        'email': 'ismed.sofyan@gmail.com',
        'gender': 'M',
        'legal_id_no': '1106052808790001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 98,
        'name': 'Ezra Walian',
        'date_of_birth': '1997-10-22',
        'domicile_city': 'Kediri',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281387329210',
        'email': 'ezra.walian@gmail.com',
        'gender': 'M',
        'legal_id_no': '3171012210970001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 99,
        'name': 'Rafael Maitimo',
        'date_of_birth': '1984-03-17',
        'domicile_city': 'Banjarmasin',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6281398212012',
        'email': 'rafael.maitimo@gmail.com',
        'gender': 'M',
        'legal_id_no': '3171011703840001',
        'isWatchlisted': False,
        'isBlacklisted': False
    },
    {
        'user_id': 100,
        'name': 'Asteriska Widiantini',
        'date_of_birth': '1988-03-06',
        'domicile_city': 'Bandung',
        'domicile_country': 'Indonesia',
        'nationality_country': 'Indonesia',
        'phone_number': '+6285629370291',
        'email': 'asteriska.widiantini@gmail.com',
        'gender': 'F',
        'legal_id_no': '3273164603880001',
        'isWatchlisted': False,
        'isBlacklisted': False
    }
]