car_brands = {
    'Alfa Romeo',
    'Aston Martin',
    'Audi',
    'Bentley',
    'BMW',
    'BYD',
    'Bugatti',
    'Chery',
    'Chevrolet',
    'Chrysler',
    'Citroen',
    'Daihatsu',
    'Daewoo',
    'Dongfeng',
    'Datsun',
    'Dacia',
    'Ferrari',
    'Fiat',
    'Ford',
    'Geely',
    'Honda',
    'Hino',
    'Hyundai',
    'Isuzu',
    'Iveco',
    'Jaguar',
    'Jeep',
    'Kia',
    'Kawasaki',
    'Lada',
    'Lamborghini',
    'Land Rover',
    'Lotus',
    'Lexus',
    'Mitsubishi',
    'McLaren',
    'Mercedes-Benz',
    'Mazda',
    'Mini',
    'Volkswagen',
    'Suzuki',
    'Mahindra',
    'Nissan',
    'Opel',
    'Peugeot',
    'Porsche',
    'Proton',
    'Renault',
    'Rolls-Royce',
    'Saab',
    'Skoda',
    'Subaru',
    'SEAT',
    'Tata',
    'Tesla',
    'Toyota',
    'UAZ',
    'Vauxhall',
    'Volvo',
    'Wuling',
    'Yamaha',
    'KAMAZ'
}

countries = {
    "Afghanistan",
    "Aland Isl.",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua-Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bonaire-Sint Eustatius-Saba",
    "Bosnia-Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Terr.",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Isl.",
    "Central African Rep.",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos Isl.",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo DR",
    "Cook Isl.",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Curacao",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Rep.",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Isl.",
    "Faroe Isl.",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Terr.",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Isl.-McDonald Isl.",
    "Vatican City",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "North Korea",
    "South Korea",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "North Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Isl.",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Isl.",
    "Northern Mariana Isl.",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn Isl.",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reunion",
    "Romania",
    "Russia",
    "Rwanda",
    "St. Barthélemy",
    "St. Helena-Ascension-Tristan da Cunha",
    "St. Kitts-Nevis",
    "St. Lucia",
    "St. Martin",
    "St. Pierre-Miquelon",
    "St. Vincent-the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome-Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "St. Maarten",
    "Slovakia",
    "Slovenia",
    "Solomon Isl.",
    "Somalia",
    "South Africa",
    "South Georgia-South Sandwich Isl.",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "South Sudan",
    "Svalbard-Jan Mayen",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad-Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks-Caicos Isl.",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "United States Minor Outlying Isl.",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "British Virgin Isl.",
    "US Virgin Isl.",
    "Wallis-Futuna",
    "Yemen",
    "Zambia",
    "Zimbabwe"
}